__STARTCODON__ = []
__AVGINTLEN__ = 0
__AVGGENELEN__ = 0
__NTFREQ__ = {}
__CODONFREQ__ = {}
__SEQ__ = {}
__NAMES__ = []
__INITPROB__ = {}
__TRANSPROB__ = {}
__INTEREMIT__ = {}
__STARTEMIT__ = {}
__GENEEMIT__ = {}
__STOPEMIT__ = {}
__STOPCODONS__ = ['TAG', 'TAA', 'TGA']